# Generated by Django 3.2.6 on 2024-01-08 20:11

from django.db import migrations, models
import django.db.models.deletion
import reserve.models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=reserve.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('building_name', models.CharField(max_length=250)),
                ('capacity', models.IntegerField()),
                ('general_info', models.TextField()),
                ('schedule', models.TextField()),
                ('services', models.TextField()),
                ('address', models.TextField()),
                ('web', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=reserve.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Space_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=reserve.models.user_directory_path)),
                ('seat_status', models.IntegerField(choices=[(0, 'FREE'), (1, 'RESERVED'), (2, 'EXPIRED'), (3, 'DISABLED')], default=0)),
                ('equipment_id', models.ManyToManyField(blank=True, to='reserve.Equipment')),
                ('space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.space')),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pplNumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='space',
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('space_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reserve.space_item')),
                ('nearby_pl', models.ManyToManyField(blank=True, related_name='_reserve_desk_nearby_pl_+', to='reserve.Desk')),
            ],
            bases=('reserve.space_item',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('space_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reserve.space_item')),
                ('capacity', models.IntegerField()),
            ],
            bases=('reserve.space_item',),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Spaces',
        ),
        migrations.AddField(
            model_name='booking',
            name='space_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reserve.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='space_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.space_item'),
        ),
    ]
