# Generated by Django 3.2.6 on 2024-01-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20240108_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='space_id',
        ),
    ]
